apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: covid-hospital-queue-dev
  name: covid-hospital-queue-dev
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-hospital-queue-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: covid-hospital-queue-dev
    spec:
      containers:
        - image: gcr.io/covid-hospital-queue/github.com/andrelnunes/covid-19
          imagePullPolicy: IfNotPresent
          name: covid-19
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: covid-hospital-queue-dev
  name: covid-hospital-queue-dev
  namespace: default
spec:
  clusterIP: 10.3.253.68
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30968
      port: 80
      protocol: TCP
      targetPort: 8501
  selector:
    app: covid-hospital-queue-dev
  sessionAffinity: None
  type: LoadBalancer